///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POC_TEST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the POC_TESTRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("06eebc44-df2f-44c2-8d03-feecc7d2a764")]
    public partial class POC_TESTRepository : RepoGenBaseFolder
    {
        static POC_TESTRepository instance = new POC_TESTRepository();
        POC_TESTRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        POC_TESTRepositoryFolders.ExplorerAppFolder _explorer;
        POC_TESTRepositoryFolders.Explorer1AppFolder _explorer1;
        POC_TESTRepositoryFolders.LoginSalesforceAppFolder _loginsalesforce;
        POC_TESTRepositoryFolders.HomeSalesforceAppFolder _homesalesforce;

        /// <summary>
        /// Gets the singleton class instance representing the POC_TESTRepository element repository.
        /// </summary>
        [RepositoryFolder("06eebc44-df2f-44c2-8d03-feecc7d2a764")]
        public static POC_TESTRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public POC_TESTRepository() 
            : base("POC_TESTRepository", "/", null, 0, false, "06eebc44-df2f-44c2-8d03-feecc7d2a764", ".\\RepositoryImages\\POC_TESTRepository06eebc44.rximgres")
        {
            _applicationundertest = new POC_TESTRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new POC_TESTRepositoryFolders.ExplorerAppFolder(this);
            _explorer1 = new POC_TESTRepositoryFolders.Explorer1AppFolder(this);
            _loginsalesforce = new POC_TESTRepositoryFolders.LoginSalesforceAppFolder(this);
            _homesalesforce = new POC_TESTRepositoryFolders.HomeSalesforceAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("06eebc44-df2f-44c2-8d03-feecc7d2a764")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("c36e43af-d1cc-4007-adcb-9df8737d2606")]
        public virtual POC_TESTRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("0a73d833-5a29-42aa-9042-5dbc17790e9e")]
        public virtual POC_TESTRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("821c6e24-a788-433c-91f8-f269c07f8bf7")]
        public virtual POC_TESTRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The LoginSalesforce folder.
        /// </summary>
        [RepositoryFolder("a9ce26a7-64b2-4dd9-87ff-352fad17ea2a")]
        public virtual POC_TESTRepositoryFolders.LoginSalesforceAppFolder LoginSalesforce
        {
            get { return _loginsalesforce; }
        }

        /// <summary>
        /// The HomeSalesforce folder.
        /// </summary>
        [RepositoryFolder("1a75e92c-1699-44f6-be70-d9cda0a9fba7")]
        public virtual POC_TESTRepositoryFolders.HomeSalesforceAppFolder HomeSalesforce
        {
            get { return _homesalesforce; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class POC_TESTRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("c36e43af-d1cc-4007-adcb-9df8737d2606")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            POC_TESTRepositoryFolders.ActionBody1Folder _actionbody1;
            POC_TESTRepositoryFolders.ViewportFolder _viewport;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _sldsiconwaffleInfo;
            RepoItemInfo _shownavigationmenuInfo;
            RepoItemInfo _projectsInfo;
            RepoItemInfo _divtagnewInfo;
            RepoItemInfo _constructionInfo;
            RepoItemInfo _dodgeInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _sldscontextbariconactionInfo;
            RepoItemInfo _lightningprimitiveiconInfo;
            RepoItemInfo _sldsdropdownlength10sldslistboxsldInfo;
            RepoItemInfo _sldstemplatecontainerInfo;
            RepoItemInfo _save1Info;
            RepoItemInfo _atagnoneInfo;
            RepoItemInfo _construction1Info;
            RepoItemInfo _actionbodyInfo;
            RepoItemInfo _windowInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='ussprod--dmibox.lightning.force.com']//header[#'oneHeader']/div[3]//button[@title='Show Navigation Menu']/tag[@tagname='lightning-primitive-icon']", parentFolder, 30000, null, false, "c36e43af-d1cc-4007-adcb-9df8737d2606", "")
            {
                _actionbody1 = new POC_TESTRepositoryFolders.ActionBody1Folder(this);
                _viewport = new POC_TESTRepositoryFolders.ViewportFolder(this);
                _logoutInfo = new RepoItemInfo(this, "LogOut", "body/div[4]/div[2]/div[2]/div[1]/div[1]/div/div[2]/div/a[@innertext='Log Out']", 30000, null, "04d64c7c-4d11-41a7-a2cf-b9014c8ef22f");
                _sldsiconwaffleInfo = new RepoItemInfo(this, "SldsIconWaffle", ".//header[#'oneHeader']/div[3]/tag/div/div/?/?/nav//div", 30000, null, "7fab390f-6648-4d27-ad1c-5ce177942c57");
                _shownavigationmenuInfo = new RepoItemInfo(this, "ShowNavigationMenu", ".//header[#'oneHeader']/div[3]/div/div[1]/div[3]/?/?/button[@title='Show Navigation Menu']", 30000, null, "aa67a88a-b37b-4206-b910-5520d701f4ed");
                _projectsInfo = new RepoItemInfo(this, "Projects", ".//div[#'navMenuList']/?/?/ul/li[16]//span[@innertext='Projects']", 30000, null, "55593436-8831-4084-9261-fcfa07fe1f48");
                _divtagnewInfo = new RepoItemInfo(this, "DivTagNew", ".//div[#'split-left']/div//ul/li[1]/a[@title='New']/div[@title='New']", 30000, null, "7ad2f2cc-8cea-42c7-a6e3-47b371d54871");
                _constructionInfo = new RepoItemInfo(this, "Construction", "body/div[7]/?/?/ul/?/?/a[@innertext='Construction']", 30000, null, "3bfb88d2-51cc-402a-82da-21614c90eba4");
                _dodgeInfo = new RepoItemInfo(this, "Dodge", "body/div[8]/?/?/ul/?/?/a[@innertext='Dodge']", 30000, null, "ae686328-1f22-4413-bff2-9adf48cd5cf5");
                _saveInfo = new RepoItemInfo(this, "Save", ".//div[#'brandBand_1']/div/div/div[2]/div/div/div[2]/button[@title='Save']", 30000, null, "af6706d0-0705-42e6-886e-c0461753caa3");
                _sldscontextbariconactionInfo = new RepoItemInfo(this, "SldsContextBarIconAction", ".//header[#'oneHeader']/div[3]/div/div[1]/div[3]/?/?/button[@title='Show Navigation Menu']/tag[@tagname='lightning-primitive-icon']", 30000, null, "14a4922f-7880-44e6-b33c-4c1fb7459e73");
                _lightningprimitiveiconInfo = new RepoItemInfo(this, "LightningPrimitiveIcon", ".//header[#'oneHeader']/div[3]//button[@title='Show Navigation Menu']/tag[@tagname='lightning-primitive-icon']", 30000, null, "8b0af015-3871-4d05-a607-baf5ec59552e");
                _sldsdropdownlength10sldslistboxsldInfo = new RepoItemInfo(this, "SldsDropdownLength10SldsListboxSld", ".//div[#'navMenuList']/?/?/ul", 30000, null, "8a8c1628-9650-4d47-a517-29d8cfb64869");
                _sldstemplatecontainerInfo = new RepoItemInfo(this, "SldsTemplateContainer", "body/div[4]/div[1]/div[2]/div[2]/div/div[2]/div/section/div/div[2]/div/div/div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[1]/div[1]//input[@type='text']", 30000, null, "9a656878-252e-448d-a2b6-f3aec43def3b");
                _save1Info = new RepoItemInfo(this, "Save1", "body/div[4]/div[1]/div[2]/div[2]/div/div[2]/div/section/div/div[2]/div/div/div/div[2]/div/div/div[2]/button[@title='Save']/span[@innertext='Save']", 30000, null, "22d055cc-c63f-439e-8e7f-e51759766041");
                _atagnoneInfo = new RepoItemInfo(this, "ATagNone", ".//div[#'brandBand_2']/div/div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[3]/div[1]/div/div/div/div/div[1]//a[@innertext='--None--']", 30000, null, "50a16208-2343-406e-a4e8-bb9904f803f5");
                _construction1Info = new RepoItemInfo(this, "Construction1", "body/div[8]/?/?/ul/?/?/a[@innertext='Construction']", 30000, null, "c5912fd8-68df-4c43-aa02-538c5f75791c");
                _actionbodyInfo = new RepoItemInfo(this, "ActionBody", ".//div[#'brandBand_2']/div/div/div[1]", 30000, null, "7a54f2bd-1c6c-45c6-9e02-95fce0e6c11f");
                _windowInfo = new RepoItemInfo(this, "Window", ".//a[#'window']", 30000, null, "4f7365fe-10f4-4839-a127-0dfc77ef548b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c36e43af-d1cc-4007-adcb-9df8737d2606")]
            public virtual Ranorex.WebElement Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c36e43af-d1cc-4007-adcb-9df8737d2606")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("04d64c7c-4d11-41a7-a2cf-b9014c8ef22f")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("04d64c7c-4d11-41a7-a2cf-b9014c8ef22f")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The SldsIconWaffle item.
            /// </summary>
            [RepositoryItem("7fab390f-6648-4d27-ad1c-5ce177942c57")]
            public virtual Ranorex.DivTag SldsIconWaffle
            {
                get
                {
                    return _sldsiconwaffleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SldsIconWaffle item info.
            /// </summary>
            [RepositoryItemInfo("7fab390f-6648-4d27-ad1c-5ce177942c57")]
            public virtual RepoItemInfo SldsIconWaffleInfo
            {
                get
                {
                    return _sldsiconwaffleInfo;
                }
            }

            /// <summary>
            /// The ShowNavigationMenu item.
            /// </summary>
            [RepositoryItem("aa67a88a-b37b-4206-b910-5520d701f4ed")]
            public virtual Ranorex.ButtonTag ShowNavigationMenu
            {
                get
                {
                    return _shownavigationmenuInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ShowNavigationMenu item info.
            /// </summary>
            [RepositoryItemInfo("aa67a88a-b37b-4206-b910-5520d701f4ed")]
            public virtual RepoItemInfo ShowNavigationMenuInfo
            {
                get
                {
                    return _shownavigationmenuInfo;
                }
            }

            /// <summary>
            /// The Projects item.
            /// </summary>
            [RepositoryItem("55593436-8831-4084-9261-fcfa07fe1f48")]
            public virtual Ranorex.SpanTag Projects
            {
                get
                {
                    return _projectsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Projects item info.
            /// </summary>
            [RepositoryItemInfo("55593436-8831-4084-9261-fcfa07fe1f48")]
            public virtual RepoItemInfo ProjectsInfo
            {
                get
                {
                    return _projectsInfo;
                }
            }

            /// <summary>
            /// The DivTagNew item.
            /// </summary>
            [RepositoryItem("7ad2f2cc-8cea-42c7-a6e3-47b371d54871")]
            public virtual Ranorex.DivTag DivTagNew
            {
                get
                {
                    return _divtagnewInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagNew item info.
            /// </summary>
            [RepositoryItemInfo("7ad2f2cc-8cea-42c7-a6e3-47b371d54871")]
            public virtual RepoItemInfo DivTagNewInfo
            {
                get
                {
                    return _divtagnewInfo;
                }
            }

            /// <summary>
            /// The Construction item.
            /// </summary>
            [RepositoryItem("3bfb88d2-51cc-402a-82da-21614c90eba4")]
            public virtual Ranorex.ATag Construction
            {
                get
                {
                    return _constructionInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Construction item info.
            /// </summary>
            [RepositoryItemInfo("3bfb88d2-51cc-402a-82da-21614c90eba4")]
            public virtual RepoItemInfo ConstructionInfo
            {
                get
                {
                    return _constructionInfo;
                }
            }

            /// <summary>
            /// The Dodge item.
            /// </summary>
            [RepositoryItem("ae686328-1f22-4413-bff2-9adf48cd5cf5")]
            public virtual Ranorex.ATag Dodge
            {
                get
                {
                    return _dodgeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Dodge item info.
            /// </summary>
            [RepositoryItemInfo("ae686328-1f22-4413-bff2-9adf48cd5cf5")]
            public virtual RepoItemInfo DodgeInfo
            {
                get
                {
                    return _dodgeInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("af6706d0-0705-42e6-886e-c0461753caa3")]
            public virtual Ranorex.ButtonTag Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("af6706d0-0705-42e6-886e-c0461753caa3")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The SldsContextBarIconAction item.
            /// </summary>
            [RepositoryItem("14a4922f-7880-44e6-b33c-4c1fb7459e73")]
            public virtual Ranorex.WebElement SldsContextBarIconAction
            {
                get
                {
                    return _sldscontextbariconactionInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The SldsContextBarIconAction item info.
            /// </summary>
            [RepositoryItemInfo("14a4922f-7880-44e6-b33c-4c1fb7459e73")]
            public virtual RepoItemInfo SldsContextBarIconActionInfo
            {
                get
                {
                    return _sldscontextbariconactionInfo;
                }
            }

            /// <summary>
            /// The LightningPrimitiveIcon item.
            /// </summary>
            [RepositoryItem("8b0af015-3871-4d05-a607-baf5ec59552e")]
            public virtual Ranorex.WebElement LightningPrimitiveIcon
            {
                get
                {
                    return _lightningprimitiveiconInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The LightningPrimitiveIcon item info.
            /// </summary>
            [RepositoryItemInfo("8b0af015-3871-4d05-a607-baf5ec59552e")]
            public virtual RepoItemInfo LightningPrimitiveIconInfo
            {
                get
                {
                    return _lightningprimitiveiconInfo;
                }
            }

            /// <summary>
            /// The SldsDropdownLength10SldsListboxSld item.
            /// </summary>
            [RepositoryItem("8a8c1628-9650-4d47-a517-29d8cfb64869")]
            public virtual Ranorex.UlTag SldsDropdownLength10SldsListboxSld
            {
                get
                {
                    return _sldsdropdownlength10sldslistboxsldInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The SldsDropdownLength10SldsListboxSld item info.
            /// </summary>
            [RepositoryItemInfo("8a8c1628-9650-4d47-a517-29d8cfb64869")]
            public virtual RepoItemInfo SldsDropdownLength10SldsListboxSldInfo
            {
                get
                {
                    return _sldsdropdownlength10sldslistboxsldInfo;
                }
            }

            /// <summary>
            /// The SldsTemplateContainer item.
            /// </summary>
            [RepositoryItem("9a656878-252e-448d-a2b6-f3aec43def3b")]
            public virtual Ranorex.InputTag SldsTemplateContainer
            {
                get
                {
                    return _sldstemplatecontainerInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SldsTemplateContainer item info.
            /// </summary>
            [RepositoryItemInfo("9a656878-252e-448d-a2b6-f3aec43def3b")]
            public virtual RepoItemInfo SldsTemplateContainerInfo
            {
                get
                {
                    return _sldstemplatecontainerInfo;
                }
            }

            /// <summary>
            /// The Save1 item.
            /// </summary>
            [RepositoryItem("22d055cc-c63f-439e-8e7f-e51759766041")]
            public virtual Ranorex.SpanTag Save1
            {
                get
                {
                    return _save1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Save1 item info.
            /// </summary>
            [RepositoryItemInfo("22d055cc-c63f-439e-8e7f-e51759766041")]
            public virtual RepoItemInfo Save1Info
            {
                get
                {
                    return _save1Info;
                }
            }

            /// <summary>
            /// The ATagNone item.
            /// </summary>
            [RepositoryItem("50a16208-2343-406e-a4e8-bb9904f803f5")]
            public virtual Ranorex.ATag ATagNone
            {
                get
                {
                    return _atagnoneInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagNone item info.
            /// </summary>
            [RepositoryItemInfo("50a16208-2343-406e-a4e8-bb9904f803f5")]
            public virtual RepoItemInfo ATagNoneInfo
            {
                get
                {
                    return _atagnoneInfo;
                }
            }

            /// <summary>
            /// The Construction1 item.
            /// </summary>
            [RepositoryItem("c5912fd8-68df-4c43-aa02-538c5f75791c")]
            public virtual Ranorex.ATag Construction1
            {
                get
                {
                    return _construction1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Construction1 item info.
            /// </summary>
            [RepositoryItemInfo("c5912fd8-68df-4c43-aa02-538c5f75791c")]
            public virtual RepoItemInfo Construction1Info
            {
                get
                {
                    return _construction1Info;
                }
            }

            /// <summary>
            /// The ActionBody item.
            /// </summary>
            [RepositoryItem("7a54f2bd-1c6c-45c6-9e02-95fce0e6c11f")]
            public virtual Ranorex.DivTag ActionBody
            {
                get
                {
                    return _actionbodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ActionBody item info.
            /// </summary>
            [RepositoryItemInfo("7a54f2bd-1c6c-45c6-9e02-95fce0e6c11f")]
            public virtual RepoItemInfo ActionBodyInfo
            {
                get
                {
                    return _actionbodyInfo;
                }
            }

            /// <summary>
            /// The Window item.
            /// </summary>
            [RepositoryItem("4f7365fe-10f4-4839-a127-0dfc77ef548b")]
            public virtual Ranorex.ATag Window
            {
                get
                {
                    return _windowInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Window item info.
            /// </summary>
            [RepositoryItemInfo("4f7365fe-10f4-4839-a127-0dfc77ef548b")]
            public virtual RepoItemInfo WindowInfo
            {
                get
                {
                    return _windowInfo;
                }
            }

            /// <summary>
            /// The ActionBody1 folder.
            /// </summary>
            [RepositoryFolder("8a8b22e1-a8a4-49f8-8cb5-8403c4dcd894")]
            public virtual POC_TESTRepositoryFolders.ActionBody1Folder ActionBody1
            {
                get { return _actionbody1; }
            }

            /// <summary>
            /// The Viewport folder.
            /// </summary>
            [RepositoryFolder("0b40a5ea-63e4-468f-a832-3a4bafb0a73d")]
            public virtual POC_TESTRepositoryFolders.ViewportFolder Viewport
            {
                get { return _viewport; }
            }
        }

        /// <summary>
        /// The ActionBody1Folder folder.
        /// </summary>
        [RepositoryFolder("8a8b22e1-a8a4-49f8-8cb5-8403c4dcd894")]
        public partial class ActionBody1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _actionbodyInfo;
            RepoItemInfo _text4Info;
            RepoItemInfo _atagnone1Info;
            RepoItemInfo _textInfo;
            RepoItemInfo _atagnoneInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _text2Info;
            RepoItemInfo _text3Info;

            /// <summary>
            /// Creates a new ActionBody1  folder.
            /// </summary>
            public ActionBody1Folder(RepoGenBaseFolder parentFolder) :
                    base("ActionBody1", ".//div[#'brandBand_1']/div/div/div[1]", parentFolder, 30000, null, false, "8a8b22e1-a8a4-49f8-8cb5-8403c4dcd894", "")
            {
                _actionbodyInfo = new RepoItemInfo(this, "ActionBody", "", 30000, null, "513642a1-923d-4658-bb39-a2257dcf60e1");
                _text4Info = new RepoItemInfo(this, "Text4", "?/?/article/div[3]/div/div[1]/div/div/div[11]/div[1]//input[@type='text']", 30000, null, "be9a5f23-d626-4bfb-8dad-574811efc07c");
                _atagnone1Info = new RepoItemInfo(this, "ATagNone1", "?/?/article/div[3]/div/div[1]/div/div/div[14]/div[1]/div/div/div/div/div[1]//a[@innertext='--None--']", 30000, null, "8a18db8c-73ec-44d2-ac8e-e61bac235e65");
                _textInfo = new RepoItemInfo(this, "Text", "?/?/article/div[3]/div/div[1]/div/div/div[1]/div[1]//input[@type='text']", 30000, null, "2bfafd95-9f47-4722-84f6-fefc5b6deced");
                _atagnoneInfo = new RepoItemInfo(this, "ATagNone", "?/?/article/div[3]/div/div[1]/div/div/div[3]/div[1]/div/div/div/div/div[1]//a[@innertext='--None--']", 30000, null, "925783e9-49ae-450d-9eb6-dd855cbece70");
                _text1Info = new RepoItemInfo(this, "Text1", "?/?/article/div[3]/div/div[1]/div/div/div[5]/div[1]//input[@type='text']", 30000, null, "380aaca8-f9f3-4db5-b9d8-62eeac8976ff");
                _text2Info = new RepoItemInfo(this, "Text2", "?/?/article/div[3]/div/div[1]/div/div/div[8]/div[1]//input[@type='text']", 30000, null, "bb809d57-25cd-4aa9-a174-47ce30480e49");
                _text3Info = new RepoItemInfo(this, "Text3", "?/?/article/div[3]/div/div[1]/div/div/div[9]/div[1]//input[@type='text']", 30000, null, "3ce0ea0f-8129-4764-a539-25dda20b2cca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8a8b22e1-a8a4-49f8-8cb5-8403c4dcd894")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8a8b22e1-a8a4-49f8-8cb5-8403c4dcd894")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ActionBody item.
            /// </summary>
            [RepositoryItem("513642a1-923d-4658-bb39-a2257dcf60e1")]
            public virtual Ranorex.DivTag ActionBody
            {
                get
                {
                    return _actionbodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ActionBody item info.
            /// </summary>
            [RepositoryItemInfo("513642a1-923d-4658-bb39-a2257dcf60e1")]
            public virtual RepoItemInfo ActionBodyInfo
            {
                get
                {
                    return _actionbodyInfo;
                }
            }

            /// <summary>
            /// The Text4 item.
            /// </summary>
            [RepositoryItem("be9a5f23-d626-4bfb-8dad-574811efc07c")]
            public virtual Ranorex.InputTag Text4
            {
                get
                {
                    return _text4Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text4 item info.
            /// </summary>
            [RepositoryItemInfo("be9a5f23-d626-4bfb-8dad-574811efc07c")]
            public virtual RepoItemInfo Text4Info
            {
                get
                {
                    return _text4Info;
                }
            }

            /// <summary>
            /// The ATagNone1 item.
            /// </summary>
            [RepositoryItem("8a18db8c-73ec-44d2-ac8e-e61bac235e65")]
            public virtual Ranorex.ATag ATagNone1
            {
                get
                {
                    return _atagnone1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagNone1 item info.
            /// </summary>
            [RepositoryItemInfo("8a18db8c-73ec-44d2-ac8e-e61bac235e65")]
            public virtual RepoItemInfo ATagNone1Info
            {
                get
                {
                    return _atagnone1Info;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("2bfafd95-9f47-4722-84f6-fefc5b6deced")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("2bfafd95-9f47-4722-84f6-fefc5b6deced")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The ATagNone item.
            /// </summary>
            [RepositoryItem("925783e9-49ae-450d-9eb6-dd855cbece70")]
            public virtual Ranorex.ATag ATagNone
            {
                get
                {
                    return _atagnoneInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagNone item info.
            /// </summary>
            [RepositoryItemInfo("925783e9-49ae-450d-9eb6-dd855cbece70")]
            public virtual RepoItemInfo ATagNoneInfo
            {
                get
                {
                    return _atagnoneInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("380aaca8-f9f3-4db5-b9d8-62eeac8976ff")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("380aaca8-f9f3-4db5-b9d8-62eeac8976ff")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("bb809d57-25cd-4aa9-a174-47ce30480e49")]
            public virtual Ranorex.InputTag Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("bb809d57-25cd-4aa9-a174-47ce30480e49")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The Text3 item.
            /// </summary>
            [RepositoryItem("3ce0ea0f-8129-4764-a539-25dda20b2cca")]
            public virtual Ranorex.InputTag Text3
            {
                get
                {
                    return _text3Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text3 item info.
            /// </summary>
            [RepositoryItemInfo("3ce0ea0f-8129-4764-a539-25dda20b2cca")]
            public virtual RepoItemInfo Text3Info
            {
                get
                {
                    return _text3Info;
                }
            }
        }

        /// <summary>
        /// The ViewportFolder folder.
        /// </summary>
        [RepositoryFolder("0b40a5ea-63e4-468f-a832-3a4bafb0a73d")]
        public partial class ViewportFolder : RepoGenBaseFolder
        {
            RepoItemInfo _carasalmonInfo;
            RepoItemInfo _viewallInfo;
            RepoItemInfo _ussInfo;
            RepoItemInfo _sldscolsldsphorizontallargesldsscInfo;
            RepoItemInfo _usscrmInfo;
            UnassignedProjectQueueInfoClass _unassignedprojectqueueInfo;
            RepoItemInfo _viewall1Info;
            RepoItemInfo _sldscolsldsphorizontallargesldssc1Info;
            RepoItemInfo _usscrm1Info;
            RepoItemInfo _someptagInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _atagnewInfo;
            RepoItemInfo _carasalmon1Info;

            /// <summary>
            /// Creates a new Viewport  folder.
            /// </summary>
            public ViewportFolder(RepoGenBaseFolder parentFolder) :
                    base("Viewport", "body/div[4]/div[2]", parentFolder, 30000, null, false, "0b40a5ea-63e4-468f-a832-3a4bafb0a73d", "")
            {
                _carasalmonInfo = new RepoItemInfo(this, "CaraSalmon", "div/div[1]/div[2]//header/div[2]/div[1]/div[2]/h1/a[@innertext='Cara Salmon']", 30000, null, "a1fff51a-2899-4b69-8831-81b6a20d5706");
                _viewallInfo = new RepoItemInfo(this, "ViewAll", "div[2]//button[@innertext='View All']", 30000, null, "02f16bfe-b96d-4c23-b29f-d523a618a27f");
                _ussInfo = new RepoItemInfo(this, "USS", "div[2]/div[2]/div/div[2]/tag/div/div[2]//section//tag[@tagname='one-app-launcher-app-tile']/div/div[2]/div/a[@href>'https://ussprod--dmibox.l']//p[@innertext='USS ']", 30000, null, "d45c154a-d3a9-4b1c-a1ed-b73b3076fd37");
                _sldscolsldsphorizontallargesldsscInfo = new RepoItemInfo(this, "SldsColSldsPHorizontalLargeSldsSc", "div[2]//tag[@tagname='one-app-launcher-modal']/div/div[2]", 30000, null, "4d25c0f6-6361-4a02-862a-1c97a21348d7");
                _usscrmInfo = new RepoItemInfo(this, "USSCRM", "", 30000, null, "8d06c565-b684-4dc7-8aa3-ac71d8315952");
                _unassignedprojectqueueInfo = new UnassignedProjectQueueInfoClass(this);
                _viewall1Info = new RepoItemInfo(this, "ViewAll1", "div/div[1]/div[1]//button[@innertext='View All']", 30000, null, "87e1128f-3cf6-4bad-b09e-b590e8889ac1");
                _sldscolsldsphorizontallargesldssc1Info = new RepoItemInfo(this, "SldsColSldsPHorizontalLargeSldsSc1", "", 30000, null, "4bebdb61-f6ac-4e00-a6bb-bbe334a01ece");
                _usscrm1Info = new RepoItemInfo(this, "USSCRM1", "", 30000, null, "56dec5cf-1183-47bd-95e8-9e5b071d7ee0");
                _someptagInfo = new RepoItemInfo(this, "SomePTag", "", 30000, null, "489c3ac3-f453-4477-a35d-283401dfdb6b");
                _searchInfo = new RepoItemInfo(this, "Search", "div[2]/div[2]//tag[@tagname='one-app-launcher-modal']/div/div[1]/div/div/?/?/tag[@tagname='lightning-input']/div/input[@type='search']", 30000, null, "76ed755b-fb50-445c-811f-11162f7f0bab");
                _atagnewInfo = new RepoItemInfo(this, "ATagNew", "div/div/div/div[1]//ul/li[1]/a[@title='New']", 30000, null, "07386cdb-5049-4921-9a7b-795015268d25");
                _carasalmon1Info = new RepoItemInfo(this, "CaraSalmon1", "div//tag[@tagname='flexipage-record-page-decorator']/div/tag[@tagname='slot']/tag/div/div[2]/div[1]//tag[@tagname='flexipage-tabset2']/div/?/?/div/tag[@tagname='slot']/?/?/tag[@tagname='slot']/tag[1]//div/div/div/tag[@tagname='records-record-layout-event-broker']//tag[@tagname='force-record-layout-block']/tag[@tagname='slot']/tag[1]/div/div/div/tag/tag[1]/tag/tag[2]/div/div/div[2]/span//div/span/?/?/div/tag[@tagname='force-hoverable-link']/div/a[@innertext='Cara Salmon']", 30000, null, "fcaefbc0-cb33-4682-94db-151d11baeb17");
            }

            /// <summary>
            /// The UnassignedProjectQueueInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("5117c245-0019-4305-82b9-49f759d25b03")]
            public class UnassignedProjectQueueInfoClass : RepoItemInfo
            {
                /// <summary>
                /// UnassignedProjectQueueInfoClass class constructor.
                /// </summary>
                public UnassignedProjectQueueInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "UnassignedProjectQueue", "", 30000, null, "5117c245-0019-4305-82b9-49f759d25b03")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("512a52a9-154f-4d15-80e1-6a3f38b26196")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("512a52a9-154f-4d15-80e1-6a3f38b26196");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("512a52a9-154f-4d15-80e1-6a3f38b26196")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("512a52a9-154f-4d15-80e1-6a3f38b26196", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0b40a5ea-63e4-468f-a832-3a4bafb0a73d")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0b40a5ea-63e4-468f-a832-3a4bafb0a73d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CaraSalmon item.
            /// </summary>
            [RepositoryItem("a1fff51a-2899-4b69-8831-81b6a20d5706")]
            public virtual Ranorex.ATag CaraSalmon
            {
                get
                {
                    return _carasalmonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CaraSalmon item info.
            /// </summary>
            [RepositoryItemInfo("a1fff51a-2899-4b69-8831-81b6a20d5706")]
            public virtual RepoItemInfo CaraSalmonInfo
            {
                get
                {
                    return _carasalmonInfo;
                }
            }

            /// <summary>
            /// The ViewAll item.
            /// </summary>
            [RepositoryItem("02f16bfe-b96d-4c23-b29f-d523a618a27f")]
            public virtual Ranorex.ButtonTag ViewAll
            {
                get
                {
                    return _viewallInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ViewAll item info.
            /// </summary>
            [RepositoryItemInfo("02f16bfe-b96d-4c23-b29f-d523a618a27f")]
            public virtual RepoItemInfo ViewAllInfo
            {
                get
                {
                    return _viewallInfo;
                }
            }

            /// <summary>
            /// The USS item.
            /// </summary>
            [RepositoryItem("d45c154a-d3a9-4b1c-a1ed-b73b3076fd37")]
            public virtual Ranorex.PTag USS
            {
                get
                {
                    return _ussInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The USS item info.
            /// </summary>
            [RepositoryItemInfo("d45c154a-d3a9-4b1c-a1ed-b73b3076fd37")]
            public virtual RepoItemInfo USSInfo
            {
                get
                {
                    return _ussInfo;
                }
            }

            /// <summary>
            /// The SldsColSldsPHorizontalLargeSldsSc item.
            /// </summary>
            [RepositoryItem("4d25c0f6-6361-4a02-862a-1c97a21348d7")]
            public virtual Ranorex.DivTag SldsColSldsPHorizontalLargeSldsSc
            {
                get
                {
                    return _sldscolsldsphorizontallargesldsscInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SldsColSldsPHorizontalLargeSldsSc item info.
            /// </summary>
            [RepositoryItemInfo("4d25c0f6-6361-4a02-862a-1c97a21348d7")]
            public virtual RepoItemInfo SldsColSldsPHorizontalLargeSldsScInfo
            {
                get
                {
                    return _sldscolsldsphorizontallargesldsscInfo;
                }
            }

            /// <summary>
            /// The USSCRM item.
            /// </summary>
            [RepositoryItem("8d06c565-b684-4dc7-8aa3-ac71d8315952")]
            public virtual Ranorex.DivTag USSCRM
            {
                get
                {
                    return _usscrmInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The USSCRM item info.
            /// </summary>
            [RepositoryItemInfo("8d06c565-b684-4dc7-8aa3-ac71d8315952")]
            public virtual RepoItemInfo USSCRMInfo
            {
                get
                {
                    return _usscrmInfo;
                }
            }

            /// <summary>
            /// The UnassignedProjectQueue item.
            /// </summary>
            [RepositoryItem("5117c245-0019-4305-82b9-49f759d25b03")]
            public virtual Ranorex.DivTag UnassignedProjectQueue
            {
                get
                {
                    return _unassignedprojectqueueInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UnassignedProjectQueue item info.
            /// </summary>
            [RepositoryItemInfo("5117c245-0019-4305-82b9-49f759d25b03")]
            public virtual UnassignedProjectQueueInfoClass UnassignedProjectQueueInfo
            {
                get
                {
                    return _unassignedprojectqueueInfo;
                }
            }

            /// <summary>
            /// The ViewAll1 item.
            /// </summary>
            [RepositoryItem("87e1128f-3cf6-4bad-b09e-b590e8889ac1")]
            public virtual Ranorex.ButtonTag ViewAll1
            {
                get
                {
                    return _viewall1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ViewAll1 item info.
            /// </summary>
            [RepositoryItemInfo("87e1128f-3cf6-4bad-b09e-b590e8889ac1")]
            public virtual RepoItemInfo ViewAll1Info
            {
                get
                {
                    return _viewall1Info;
                }
            }

            /// <summary>
            /// The SldsColSldsPHorizontalLargeSldsSc1 item.
            /// </summary>
            [RepositoryItem("4bebdb61-f6ac-4e00-a6bb-bbe334a01ece")]
            public virtual Ranorex.DivTag SldsColSldsPHorizontalLargeSldsSc1
            {
                get
                {
                    return _sldscolsldsphorizontallargesldssc1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SldsColSldsPHorizontalLargeSldsSc1 item info.
            /// </summary>
            [RepositoryItemInfo("4bebdb61-f6ac-4e00-a6bb-bbe334a01ece")]
            public virtual RepoItemInfo SldsColSldsPHorizontalLargeSldsSc1Info
            {
                get
                {
                    return _sldscolsldsphorizontallargesldssc1Info;
                }
            }

            /// <summary>
            /// The USSCRM1 item.
            /// </summary>
            [RepositoryItem("56dec5cf-1183-47bd-95e8-9e5b071d7ee0")]
            public virtual Ranorex.DivTag USSCRM1
            {
                get
                {
                    return _usscrm1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The USSCRM1 item info.
            /// </summary>
            [RepositoryItemInfo("56dec5cf-1183-47bd-95e8-9e5b071d7ee0")]
            public virtual RepoItemInfo USSCRM1Info
            {
                get
                {
                    return _usscrm1Info;
                }
            }

            /// <summary>
            /// The SomePTag item.
            /// </summary>
            [RepositoryItem("489c3ac3-f453-4477-a35d-283401dfdb6b")]
            public virtual Ranorex.DivTag SomePTag
            {
                get
                {
                    return _someptagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomePTag item info.
            /// </summary>
            [RepositoryItemInfo("489c3ac3-f453-4477-a35d-283401dfdb6b")]
            public virtual RepoItemInfo SomePTagInfo
            {
                get
                {
                    return _someptagInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("76ed755b-fb50-445c-811f-11162f7f0bab")]
            public virtual Ranorex.InputTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("76ed755b-fb50-445c-811f-11162f7f0bab")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The ATagNew item.
            /// </summary>
            [RepositoryItem("07386cdb-5049-4921-9a7b-795015268d25")]
            public virtual Ranorex.ATag ATagNew
            {
                get
                {
                    return _atagnewInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagNew item info.
            /// </summary>
            [RepositoryItemInfo("07386cdb-5049-4921-9a7b-795015268d25")]
            public virtual RepoItemInfo ATagNewInfo
            {
                get
                {
                    return _atagnewInfo;
                }
            }

            /// <summary>
            /// The CaraSalmon1 item.
            /// </summary>
            [RepositoryItem("fcaefbc0-cb33-4682-94db-151d11baeb17")]
            public virtual Ranorex.ATag CaraSalmon1
            {
                get
                {
                    return _carasalmon1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CaraSalmon1 item info.
            /// </summary>
            [RepositoryItemInfo("fcaefbc0-cb33-4682-94db-151d11baeb17")]
            public virtual RepoItemInfo CaraSalmon1Info
            {
                get
                {
                    return _carasalmon1Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("0a73d833-5a29-42aa-9042-5dbc17790e9e")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginsalesforcegooglechromeInfo;
            RepoItemInfo _homesalesforcegooglechromeInfo;
            RepoItemInfo _listitemInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/form[@title='']", parentFolder, 30000, null, true, "0a73d833-5a29-42aa-9042-5dbc17790e9e", "")
            {
                _loginsalesforcegooglechromeInfo = new RepoItemInfo(this, "LoginSalesforceGoogleChrome", "?/?/listitem[@accessiblename>'Login | Salesforce - Google']", 30000, null, "6ce6af63-74eb-4e23-9d84-b0e3ded6aeee");
                _homesalesforcegooglechromeInfo = new RepoItemInfo(this, "HomeSalesforceGoogleChrome", "?/?/listitem[@accessiblename>'Home | Salesforce - Google']", 30000, null, "98b41642-de20-473c-b754-86a0683cc1af");
                _listitemInfo = new RepoItemInfo(this, "ListItem", "?/?/listitem", 30000, null, "53b832e7-383f-4458-b9ba-0584e307511d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0a73d833-5a29-42aa-9042-5dbc17790e9e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a73d833-5a29-42aa-9042-5dbc17790e9e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginSalesforceGoogleChrome item.
            /// </summary>
            [RepositoryItem("6ce6af63-74eb-4e23-9d84-b0e3ded6aeee")]
            public virtual Ranorex.ListItem LoginSalesforceGoogleChrome
            {
                get
                {
                    return _loginsalesforcegooglechromeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The LoginSalesforceGoogleChrome item info.
            /// </summary>
            [RepositoryItemInfo("6ce6af63-74eb-4e23-9d84-b0e3ded6aeee")]
            public virtual RepoItemInfo LoginSalesforceGoogleChromeInfo
            {
                get
                {
                    return _loginsalesforcegooglechromeInfo;
                }
            }

            /// <summary>
            /// The HomeSalesforceGoogleChrome item.
            /// </summary>
            [RepositoryItem("98b41642-de20-473c-b754-86a0683cc1af")]
            public virtual Ranorex.ListItem HomeSalesforceGoogleChrome
            {
                get
                {
                    return _homesalesforcegooglechromeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The HomeSalesforceGoogleChrome item info.
            /// </summary>
            [RepositoryItemInfo("98b41642-de20-473c-b754-86a0683cc1af")]
            public virtual RepoItemInfo HomeSalesforceGoogleChromeInfo
            {
                get
                {
                    return _homesalesforcegooglechromeInfo;
                }
            }

            /// <summary>
            /// The ListItem item.
            /// </summary>
            [RepositoryItem("53b832e7-383f-4458-b9ba-0584e307511d")]
            public virtual Ranorex.ListItem ListItem
            {
                get
                {
                    return _listitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem item info.
            /// </summary>
            [RepositoryItemInfo("53b832e7-383f-4458-b9ba-0584e307511d")]
            public virtual RepoItemInfo ListItemInfo
            {
                get
                {
                    return _listitemInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("821c6e24-a788-433c-91f8-f269c07f8bf7")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechrome1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "821c6e24-a788-433c-91f8-f269c07f8bf7", "")
            {
                _googlechrome1runningwindowInfo = new RepoItemInfo(this, "GoogleChrome1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[3]", 30000, null, "84d0438d-f60a-4bdf-95c8-0ff978cebf32");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("821c6e24-a788-433c-91f8-f269c07f8bf7")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("821c6e24-a788-433c-91f8-f269c07f8bf7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item.
            /// </summary>
            [RepositoryItem("84d0438d-f60a-4bdf-95c8-0ff978cebf32")]
            public virtual Ranorex.Button GoogleChrome1RunningWindow
            {
                get
                {
                    return _googlechrome1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("84d0438d-f60a-4bdf-95c8-0ff978cebf32")]
            public virtual RepoItemInfo GoogleChrome1RunningWindowInfo
            {
                get
                {
                    return _googlechrome1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The LoginSalesforceAppFolder folder.
        /// </summary>
        [RepositoryFolder("a9ce26a7-64b2-4dd9-87ff-352fad17ea2a")]
        public partial class LoginSalesforceAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new LoginSalesforce  folder.
            /// </summary>
            public LoginSalesforceAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginSalesforce", "/dom[@domain='ussprod--dmibox.my.salesforce.com']", parentFolder, 30000, null, false, "a9ce26a7-64b2-4dd9-87ff-352fad17ea2a", "")
            {
                _loginInfo = new RepoItemInfo(this, "Login", ".//input[#'Login']", 30000, null, "af1173b6-97c7-4351-9bed-e59ab7e5e043");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a9ce26a7-64b2-4dd9-87ff-352fad17ea2a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a9ce26a7-64b2-4dd9-87ff-352fad17ea2a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("af1173b6-97c7-4351-9bed-e59ab7e5e043")]
            public virtual Ranorex.InputTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("af1173b6-97c7-4351-9bed-e59ab7e5e043")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The HomeSalesforceAppFolder folder.
        /// </summary>
        [RepositoryFolder("1a75e92c-1699-44f6-be70-d9cda0a9fba7")]
        public partial class HomeSalesforceAppFolder : RepoGenBaseFolder
        {
            POC_TESTRepositoryFolders.FullRightMainContentFolder _fullrightmaincontent;
            POC_TESTRepositoryFolders.SldsTemplateContainer1Folder _sldstemplatecontainer1;
            RepoItemInfo _uiimageInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _sldsr2Info;
            RepoItemInfo _lightningprimitiveiconInfo;
            RepoItemInfo _sldsdropdownlength10sldslistboxsldInfo;
            RepoItemInfo _projectsInfo;
            RepoItemInfo _divtagnewInfo;
            RepoItemInfo _constructionInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _construction1Info;

            /// <summary>
            /// Creates a new HomeSalesforce  folder.
            /// </summary>
            public HomeSalesforceAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HomeSalesforce", "/dom[@domain='ussprod--dmibox.lightning.force.com']", parentFolder, 30000, null, false, "1a75e92c-1699-44f6-be70-d9cda0a9fba7", "")
            {
                _fullrightmaincontent = new POC_TESTRepositoryFolders.FullRightMainContentFolder(this);
                _sldstemplatecontainer1 = new POC_TESTRepositoryFolders.SldsTemplateContainer1Folder(this);
                _uiimageInfo = new RepoItemInfo(this, "UiImage", ".//header[#'oneHeader']/div[2]/span/?/?/ul/li[9]//div/span[1]/div/span[@visible='True']", 30000, null, "2c37ca8b-7e1c-4de4-82ee-580fafdc8e40");
                _logoutInfo = new RepoItemInfo(this, "LogOut", "body/div[4]/div[2]/div[3]/div[1]/div[1]/div/div[2]/?/?/a[@innertext='Log Out' and @safeclass='logout profile-link-label uiOutputURL' and @class='profile-link-label logout uiOutputURL']", 30000, null, "92a4a1c0-75bb-4bf9-a612-67169615139a");
                _sldsr2Info = new RepoItemInfo(this, "SldsR2", ".//header[#'oneHeader']/div[3]/div/div[1]/div[1]/nav/button/div/div/div[2]", 30000, null, "a2e4071b-c510-47c3-b225-438fc4c9977f");
                _lightningprimitiveiconInfo = new RepoItemInfo(this, "LightningPrimitiveIcon", ".//header[#'oneHeader']/div[3]//button[@title='Show Navigation Menu']/tag[@tagname='lightning-primitive-icon']", 30000, null, "fd5f834d-3d1e-4265-9444-0aa1bf2097c6");
                _sldsdropdownlength10sldslistboxsldInfo = new RepoItemInfo(this, "SldsDropdownLength10SldsListboxSld", ".//div[#'navMenuList']/?/?/ul", 30000, null, "ae752c0f-814f-48c9-a077-0d94e1c8eba7");
                _projectsInfo = new RepoItemInfo(this, "Projects", ".//div[#'navMenuList']/?/?/ul/li[16]//span[@innertext='Projects']", 30000, null, "6406eff9-58fd-42e1-af32-741ed5ac0d04");
                _divtagnewInfo = new RepoItemInfo(this, "DivTagNew", ".//div[#'split-left']/div//ul/li[1]/a[@title='New']/div[@title='New']", 30000, null, "c3e9a59b-6281-4c2b-ba4a-e639b02dde2c");
                _constructionInfo = new RepoItemInfo(this, "Construction", "body/div[8]/?/?/ul/?/?/a[@innertext='Construction']", 30000, null, "d7105e6a-abb9-42d0-91be-aef8369d9ef0");
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'brandBand_1']/div/div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[1]/div[1]//input[@type='text']", 30000, null, "1a6bab8e-718f-4544-9f42-7f96dba3ed3f");
                _construction1Info = new RepoItemInfo(this, "Construction1", "body/div[7]/?/?/ul/?/?/a[@innertext='Construction']", 30000, null, "fc9a7499-ff39-4994-ae4b-a953bc3f77f3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a75e92c-1699-44f6-be70-d9cda0a9fba7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a75e92c-1699-44f6-be70-d9cda0a9fba7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UiImage item.
            /// </summary>
            [RepositoryItem("2c37ca8b-7e1c-4de4-82ee-580fafdc8e40")]
            public virtual Ranorex.SpanTag UiImage
            {
                get
                {
                    return _uiimageInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UiImage item info.
            /// </summary>
            [RepositoryItemInfo("2c37ca8b-7e1c-4de4-82ee-580fafdc8e40")]
            public virtual RepoItemInfo UiImageInfo
            {
                get
                {
                    return _uiimageInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("92a4a1c0-75bb-4bf9-a612-67169615139a")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("92a4a1c0-75bb-4bf9-a612-67169615139a")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The SldsR2 item.
            /// </summary>
            [RepositoryItem("a2e4071b-c510-47c3-b225-438fc4c9977f")]
            public virtual Ranorex.DivTag SldsR2
            {
                get
                {
                    return _sldsr2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SldsR2 item info.
            /// </summary>
            [RepositoryItemInfo("a2e4071b-c510-47c3-b225-438fc4c9977f")]
            public virtual RepoItemInfo SldsR2Info
            {
                get
                {
                    return _sldsr2Info;
                }
            }

            /// <summary>
            /// The LightningPrimitiveIcon item.
            /// </summary>
            [RepositoryItem("fd5f834d-3d1e-4265-9444-0aa1bf2097c6")]
            public virtual Ranorex.WebElement LightningPrimitiveIcon
            {
                get
                {
                    return _lightningprimitiveiconInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The LightningPrimitiveIcon item info.
            /// </summary>
            [RepositoryItemInfo("fd5f834d-3d1e-4265-9444-0aa1bf2097c6")]
            public virtual RepoItemInfo LightningPrimitiveIconInfo
            {
                get
                {
                    return _lightningprimitiveiconInfo;
                }
            }

            /// <summary>
            /// The SldsDropdownLength10SldsListboxSld item.
            /// </summary>
            [RepositoryItem("ae752c0f-814f-48c9-a077-0d94e1c8eba7")]
            public virtual Ranorex.UlTag SldsDropdownLength10SldsListboxSld
            {
                get
                {
                    return _sldsdropdownlength10sldslistboxsldInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The SldsDropdownLength10SldsListboxSld item info.
            /// </summary>
            [RepositoryItemInfo("ae752c0f-814f-48c9-a077-0d94e1c8eba7")]
            public virtual RepoItemInfo SldsDropdownLength10SldsListboxSldInfo
            {
                get
                {
                    return _sldsdropdownlength10sldslistboxsldInfo;
                }
            }

            /// <summary>
            /// The Projects item.
            /// </summary>
            [RepositoryItem("6406eff9-58fd-42e1-af32-741ed5ac0d04")]
            public virtual Ranorex.SpanTag Projects
            {
                get
                {
                    return _projectsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Projects item info.
            /// </summary>
            [RepositoryItemInfo("6406eff9-58fd-42e1-af32-741ed5ac0d04")]
            public virtual RepoItemInfo ProjectsInfo
            {
                get
                {
                    return _projectsInfo;
                }
            }

            /// <summary>
            /// The DivTagNew item.
            /// </summary>
            [RepositoryItem("c3e9a59b-6281-4c2b-ba4a-e639b02dde2c")]
            public virtual Ranorex.DivTag DivTagNew
            {
                get
                {
                    return _divtagnewInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagNew item info.
            /// </summary>
            [RepositoryItemInfo("c3e9a59b-6281-4c2b-ba4a-e639b02dde2c")]
            public virtual RepoItemInfo DivTagNewInfo
            {
                get
                {
                    return _divtagnewInfo;
                }
            }

            /// <summary>
            /// The Construction item.
            /// </summary>
            [RepositoryItem("d7105e6a-abb9-42d0-91be-aef8369d9ef0")]
            public virtual Ranorex.ATag Construction
            {
                get
                {
                    return _constructionInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Construction item info.
            /// </summary>
            [RepositoryItemInfo("d7105e6a-abb9-42d0-91be-aef8369d9ef0")]
            public virtual RepoItemInfo ConstructionInfo
            {
                get
                {
                    return _constructionInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("1a6bab8e-718f-4544-9f42-7f96dba3ed3f")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("1a6bab8e-718f-4544-9f42-7f96dba3ed3f")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Construction1 item.
            /// </summary>
            [RepositoryItem("fc9a7499-ff39-4994-ae4b-a953bc3f77f3")]
            public virtual Ranorex.ATag Construction1
            {
                get
                {
                    return _construction1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Construction1 item info.
            /// </summary>
            [RepositoryItemInfo("fc9a7499-ff39-4994-ae4b-a953bc3f77f3")]
            public virtual RepoItemInfo Construction1Info
            {
                get
                {
                    return _construction1Info;
                }
            }

            /// <summary>
            /// The FullRightMainContent folder.
            /// </summary>
            [RepositoryFolder("1d137b19-33d3-4271-9137-c7c775bfc2dd")]
            public virtual POC_TESTRepositoryFolders.FullRightMainContentFolder FullRightMainContent
            {
                get { return _fullrightmaincontent; }
            }

            /// <summary>
            /// The SldsTemplateContainer1 folder.
            /// </summary>
            [RepositoryFolder("febaee66-4e41-44b5-a1e7-d18b292ed6ea")]
            public virtual POC_TESTRepositoryFolders.SldsTemplateContainer1Folder SldsTemplateContainer1
            {
                get { return _sldstemplatecontainer1; }
            }
        }

        /// <summary>
        /// The FullRightMainContentFolder folder.
        /// </summary>
        [RepositoryFolder("1d137b19-33d3-4271-9137-c7c775bfc2dd")]
        public partial class FullRightMainContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _viewallInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _ussInfo;
            RepoItemInfo _carasalmonInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new FullRightMainContent  folder.
            /// </summary>
            public FullRightMainContentFolder(RepoGenBaseFolder parentFolder) :
                    base("FullRightMainContent", "body/div[4]/div[2]/div[2]", parentFolder, 30000, null, false, "1d137b19-33d3-4271-9137-c7c775bfc2dd", "")
            {
                _viewallInfo = new RepoItemInfo(this, "ViewAll", ".//button[@innertext='View All']", 30000, null, "4e0db794-fee9-4f72-be11-7a7c3a33c03f");
                _searchInfo = new RepoItemInfo(this, "Search", "div[2]//tag[@tagname='one-app-launcher-modal']/div/div[1]/div/div/?/?/tag[@tagname='lightning-input']/div/input[@type='search']", 30000, null, "3c9a8194-736d-4890-9d6e-61b6d68e0eb8");
                _ussInfo = new RepoItemInfo(this, "USS", "div[2]/div/div[2]/tag/div/div[2]//section//tag[@tagname='one-app-launcher-app-tile']/div/div[2]/div/a[@href>'https://ussprod--dmibox.l']//p[@innertext='USS ']", 30000, null, "110e954f-cf4c-47ae-9c21-c35c5103ca55");
                _carasalmonInfo = new RepoItemInfo(this, "CaraSalmon", ".//tag[@tagname='flexipage-record-page-decorator']/div/tag[@tagname='slot']/tag/div/div[2]/div[1]//tag[@tagname='flexipage-tabset2']/div/?/?/div/tag[@tagname='slot']/?/?/tag[@tagname='slot']/tag[1]//div/div/div/tag[@tagname='records-record-layout-event-broker']//tag[@tagname='force-record-layout-block']/tag[@tagname='slot']/tag[1]/div/div/div/tag/tag[1]/tag/tag[2]/div/div/div[2]/span//div/span/?/?/div/tag[@tagname='force-hoverable-link']/div/a[@innertext='Cara Salmon']", 30000, null, "665fc4a7-10ed-4579-ac4e-c1ea880c8daa");
                _logoutInfo = new RepoItemInfo(this, "LogOut", "div[1]/div[1]/div/div[2]/div/a[@href='https://ussprod--dmibox.lightning.force.com/secur/logout.jsp' and @title='' and @class='profile-link-label logout uiOutputURL']", 30000, null, "22c5d6a9-5cd0-422d-9528-fd3cfb1ac593");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1d137b19-33d3-4271-9137-c7c775bfc2dd")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1d137b19-33d3-4271-9137-c7c775bfc2dd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViewAll item.
            /// </summary>
            [RepositoryItem("4e0db794-fee9-4f72-be11-7a7c3a33c03f")]
            public virtual Ranorex.ButtonTag ViewAll
            {
                get
                {
                    return _viewallInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ViewAll item info.
            /// </summary>
            [RepositoryItemInfo("4e0db794-fee9-4f72-be11-7a7c3a33c03f")]
            public virtual RepoItemInfo ViewAllInfo
            {
                get
                {
                    return _viewallInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("3c9a8194-736d-4890-9d6e-61b6d68e0eb8")]
            public virtual Ranorex.InputTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("3c9a8194-736d-4890-9d6e-61b6d68e0eb8")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The USS item.
            /// </summary>
            [RepositoryItem("110e954f-cf4c-47ae-9c21-c35c5103ca55")]
            public virtual Ranorex.PTag USS
            {
                get
                {
                    return _ussInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The USS item info.
            /// </summary>
            [RepositoryItemInfo("110e954f-cf4c-47ae-9c21-c35c5103ca55")]
            public virtual RepoItemInfo USSInfo
            {
                get
                {
                    return _ussInfo;
                }
            }

            /// <summary>
            /// The CaraSalmon item.
            /// </summary>
            [RepositoryItem("665fc4a7-10ed-4579-ac4e-c1ea880c8daa")]
            public virtual Ranorex.ATag CaraSalmon
            {
                get
                {
                    return _carasalmonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CaraSalmon item info.
            /// </summary>
            [RepositoryItemInfo("665fc4a7-10ed-4579-ac4e-c1ea880c8daa")]
            public virtual RepoItemInfo CaraSalmonInfo
            {
                get
                {
                    return _carasalmonInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("22c5d6a9-5cd0-422d-9528-fd3cfb1ac593")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("22c5d6a9-5cd0-422d-9528-fd3cfb1ac593")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }
        }

        /// <summary>
        /// The SldsTemplateContainer1Folder folder.
        /// </summary>
        [RepositoryFolder("febaee66-4e41-44b5-a1e7-d18b292ed6ea")]
        public partial class SldsTemplateContainer1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _sldstemplatecontainerInfo;
            RepoItemInfo _actionbodyInfo;
            RepoItemInfo _text3Info;
            RepoItemInfo _textInfo;
            RepoItemInfo _atagnoneInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _text2Info;
            RepoItemInfo _text4Info;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new SldsTemplateContainer1  folder.
            /// </summary>
            public SldsTemplateContainer1Folder(RepoGenBaseFolder parentFolder) :
                    base("SldsTemplateContainer1", ".//div[#'brandBand_2']/div", parentFolder, 30000, null, false, "febaee66-4e41-44b5-a1e7-d18b292ed6ea", "")
            {
                _sldstemplatecontainerInfo = new RepoItemInfo(this, "SldsTemplateContainer", "", 30000, null, "9e2c51b0-4336-4a84-8191-6280c3dc3ecc");
                _actionbodyInfo = new RepoItemInfo(this, "ActionBody", "div/div[1]", 30000, null, "42c911ec-1c1c-4bfd-bd7d-5ef5d1d289aa");
                _text3Info = new RepoItemInfo(this, "Text3", "div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[11]/div[1]//input[@type='text']", 30000, null, "b0af3318-7e0d-416a-9453-44bcaddda97a");
                _textInfo = new RepoItemInfo(this, "Text", "div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[1]/div[1]//input[@type='text']", 30000, null, "3f51d4ed-bcd1-498c-ba88-8216afe76608");
                _atagnoneInfo = new RepoItemInfo(this, "ATagNone", "div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[3]/div[1]/div/div/div/div/div[1]//a[@innertext='--None--']", 30000, null, "ba058592-0a8b-4a37-90a3-1dc8d25c39df");
                _text1Info = new RepoItemInfo(this, "Text1", "div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[5]/div[1]//input[@type='text']", 30000, null, "4820c98a-7b78-4ff2-90ed-5d445cb9b4b7");
                _text2Info = new RepoItemInfo(this, "Text2", "div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[8]/div[1]//input[@type='text']", 30000, null, "5c45c7de-2601-465f-8886-24098374b213");
                _text4Info = new RepoItemInfo(this, "Text4", "div/div[1]/?/?/article/div[3]/div/div[1]/div/div/div[9]/div[1]//input[@type='text']", 30000, null, "5e988b43-cd31-4338-8a13-99e3f74cd807");
                _saveInfo = new RepoItemInfo(this, "Save", "div/div[2]/div/div/div[2]/button[@title='Save']/span[@innertext='Save']", 30000, null, "0ff7a903-ebc7-4a25-ac12-d3d801dda95e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("febaee66-4e41-44b5-a1e7-d18b292ed6ea")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("febaee66-4e41-44b5-a1e7-d18b292ed6ea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SldsTemplateContainer item.
            /// </summary>
            [RepositoryItem("9e2c51b0-4336-4a84-8191-6280c3dc3ecc")]
            public virtual Ranorex.DivTag SldsTemplateContainer
            {
                get
                {
                    return _sldstemplatecontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SldsTemplateContainer item info.
            /// </summary>
            [RepositoryItemInfo("9e2c51b0-4336-4a84-8191-6280c3dc3ecc")]
            public virtual RepoItemInfo SldsTemplateContainerInfo
            {
                get
                {
                    return _sldstemplatecontainerInfo;
                }
            }

            /// <summary>
            /// The ActionBody item.
            /// </summary>
            [RepositoryItem("42c911ec-1c1c-4bfd-bd7d-5ef5d1d289aa")]
            public virtual Ranorex.DivTag ActionBody
            {
                get
                {
                    return _actionbodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ActionBody item info.
            /// </summary>
            [RepositoryItemInfo("42c911ec-1c1c-4bfd-bd7d-5ef5d1d289aa")]
            public virtual RepoItemInfo ActionBodyInfo
            {
                get
                {
                    return _actionbodyInfo;
                }
            }

            /// <summary>
            /// The Text3 item.
            /// </summary>
            [RepositoryItem("b0af3318-7e0d-416a-9453-44bcaddda97a")]
            public virtual Ranorex.InputTag Text3
            {
                get
                {
                    return _text3Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text3 item info.
            /// </summary>
            [RepositoryItemInfo("b0af3318-7e0d-416a-9453-44bcaddda97a")]
            public virtual RepoItemInfo Text3Info
            {
                get
                {
                    return _text3Info;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("3f51d4ed-bcd1-498c-ba88-8216afe76608")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("3f51d4ed-bcd1-498c-ba88-8216afe76608")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The ATagNone item.
            /// </summary>
            [RepositoryItem("ba058592-0a8b-4a37-90a3-1dc8d25c39df")]
            public virtual Ranorex.ATag ATagNone
            {
                get
                {
                    return _atagnoneInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagNone item info.
            /// </summary>
            [RepositoryItemInfo("ba058592-0a8b-4a37-90a3-1dc8d25c39df")]
            public virtual RepoItemInfo ATagNoneInfo
            {
                get
                {
                    return _atagnoneInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("4820c98a-7b78-4ff2-90ed-5d445cb9b4b7")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("4820c98a-7b78-4ff2-90ed-5d445cb9b4b7")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("5c45c7de-2601-465f-8886-24098374b213")]
            public virtual Ranorex.InputTag Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("5c45c7de-2601-465f-8886-24098374b213")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The Text4 item.
            /// </summary>
            [RepositoryItem("5e988b43-cd31-4338-8a13-99e3f74cd807")]
            public virtual Ranorex.InputTag Text4
            {
                get
                {
                    return _text4Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text4 item info.
            /// </summary>
            [RepositoryItemInfo("5e988b43-cd31-4338-8a13-99e3f74cd807")]
            public virtual RepoItemInfo Text4Info
            {
                get
                {
                    return _text4Info;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("0ff7a903-ebc7-4a25-ac12-d3d801dda95e")]
            public virtual Ranorex.SpanTag Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("0ff7a903-ebc7-4a25-ac12-d3d801dda95e")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
