///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace POC_TEST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProjectOwnership_Conditional_Test recording.
    /// </summary>
    [TestModule("c4e83413-c0d0-435b-8b03-bb560cedfc01", ModuleType.Recording, 1)]
    public partial class ProjectOwnership_Conditional_Test : ITestModule
    {
        /// <summary>
        /// Holds an instance of the POC_TESTRepository repository.
        /// </summary>
        public static POC_TESTRepository repo = POC_TESTRepository.Instance;

        static ProjectOwnership_Conditional_Test instance = new ProjectOwnership_Conditional_Test();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProjectOwnership_Conditional_Test()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProjectOwnership_Conditional_Test Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.SldsR2' at 6;9.", repo.HomeSalesforce.SldsR2Info, new RecordItemIndex(0));
            repo.HomeSalesforce.SldsR2.Click("6;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.FullRightMainContent.ViewAll' at 44;14.", repo.HomeSalesforce.FullRightMainContent.ViewAllInfo, new RecordItemIndex(1));
            repo.HomeSalesforce.FullRightMainContent.ViewAll.Click("44;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.FullRightMainContent.Search' at 88;21.", repo.HomeSalesforce.FullRightMainContent.SearchInfo, new RecordItemIndex(2));
            repo.HomeSalesforce.FullRightMainContent.Search.Click("88;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'crm' with focus on 'HomeSalesforce.FullRightMainContent.Search'.", repo.HomeSalesforce.FullRightMainContent.SearchInfo, new RecordItemIndex(3));
            repo.HomeSalesforce.FullRightMainContent.Search.PressKeys("crm");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.FullRightMainContent.USS' at 46;16.", repo.HomeSalesforce.FullRightMainContent.USSInfo, new RecordItemIndex(4));
            repo.HomeSalesforce.FullRightMainContent.USS.Click("46;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(5));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.LightningPrimitiveIcon' at 10;8.", repo.HomeSalesforce.LightningPrimitiveIconInfo, new RecordItemIndex(6));
            repo.HomeSalesforce.LightningPrimitiveIcon.Click("10;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'HomeSalesforce.SldsDropdownLength10SldsListboxSld' at 320;271.", repo.HomeSalesforce.SldsDropdownLength10SldsListboxSldInfo, new RecordItemIndex(7));
            repo.HomeSalesforce.SldsDropdownLength10SldsListboxSld.MoveTo("320;271");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.Projects' at 34;8.", repo.HomeSalesforce.ProjectsInfo, new RecordItemIndex(8));
            repo.HomeSalesforce.Projects.Click("34;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(9));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.DivTagNew' at 14;21.", repo.HomeSalesforce.DivTagNewInfo, new RecordItemIndex(10));
            repo.HomeSalesforce.DivTagNew.Click("14;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.SldsTemplateContainer1.Text3' at 140;36.", repo.HomeSalesforce.SldsTemplateContainer1.Text3Info, new RecordItemIndex(11));
            repo.HomeSalesforce.SldsTemplateContainer1.Text3.Click("140;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'TESTJULY2020' with focus on 'HomeSalesforce.SldsTemplateContainer1.Text'.", repo.HomeSalesforce.SldsTemplateContainer1.TextInfo, new RecordItemIndex(12));
            repo.HomeSalesforce.SldsTemplateContainer1.Text.PressKeys("TESTJULY2020");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.SldsTemplateContainer1.ATagNone' at 139;18.", repo.HomeSalesforce.SldsTemplateContainer1.ATagNoneInfo, new RecordItemIndex(13));
            repo.HomeSalesforce.SldsTemplateContainer1.ATagNone.Click("139;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(14));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.Construction1' at 88;28.", repo.HomeSalesforce.Construction1Info, new RecordItemIndex(15));
            repo.HomeSalesforce.Construction1.Click("88;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.SldsTemplateContainer1.Text1' at 58;14.", repo.HomeSalesforce.SldsTemplateContainer1.Text1Info, new RecordItemIndex(16));
            repo.HomeSalesforce.SldsTemplateContainer1.Text1.Click("58;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '334 Drive' with focus on 'HomeSalesforce.SldsTemplateContainer1.Text1'.", repo.HomeSalesforce.SldsTemplateContainer1.Text1Info, new RecordItemIndex(17));
            repo.HomeSalesforce.SldsTemplateContainer1.Text1.PressKeys("334 Drive");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.SldsTemplateContainer1.Text2' at 42;13.", repo.HomeSalesforce.SldsTemplateContainer1.Text2Info, new RecordItemIndex(18));
            repo.HomeSalesforce.SldsTemplateContainer1.Text2.Click("42;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Westborough' with focus on 'HomeSalesforce.SldsTemplateContainer1.Text2'.", repo.HomeSalesforce.SldsTemplateContainer1.Text2Info, new RecordItemIndex(19));
            repo.HomeSalesforce.SldsTemplateContainer1.Text2.PressKeys("Westborough");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'HomeSalesforce.SldsTemplateContainer1.ActionBody' at 1280;106.", repo.HomeSalesforce.SldsTemplateContainer1.ActionBodyInfo, new RecordItemIndex(20));
            repo.HomeSalesforce.SldsTemplateContainer1.ActionBody.MoveTo("1280;106");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'HomeSalesforce.SldsTemplateContainer1.ActionBody' at 1286;195.", repo.HomeSalesforce.SldsTemplateContainer1.ActionBodyInfo, new RecordItemIndex(21));
            repo.HomeSalesforce.SldsTemplateContainer1.ActionBody.MoveTo("1286;195");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.SldsTemplateContainer1.Text4' at 54;18.", repo.HomeSalesforce.SldsTemplateContainer1.Text4Info, new RecordItemIndex(22));
            repo.HomeSalesforce.SldsTemplateContainer1.Text4.Click("54;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '01581' with focus on 'HomeSalesforce.SldsTemplateContainer1.Text4'.", repo.HomeSalesforce.SldsTemplateContainer1.Text4Info, new RecordItemIndex(23));
            repo.HomeSalesforce.SldsTemplateContainer1.Text4.PressKeys("01581");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.SldsTemplateContainer1.Text3' at 66;14.", repo.HomeSalesforce.SldsTemplateContainer1.Text3Info, new RecordItemIndex(24));
            repo.HomeSalesforce.SldsTemplateContainer1.Text3.Click("66;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5.1M' with focus on 'HomeSalesforce.SldsTemplateContainer1.Text3'.", repo.HomeSalesforce.SldsTemplateContainer1.Text3Info, new RecordItemIndex(25));
            repo.HomeSalesforce.SldsTemplateContainer1.Text3.PressKeys("5.1M");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeSalesforce.SldsTemplateContainer1.Save' at 26;19.", repo.HomeSalesforce.SldsTemplateContainer1.SaveInfo, new RecordItemIndex(26));
            repo.HomeSalesforce.SldsTemplateContainer1.Save.Click("26;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Cara Salmon') on item 'HomeSalesforce.FullRightMainContent.CaraSalmon'.", repo.HomeSalesforce.FullRightMainContent.CaraSalmonInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.HomeSalesforce.FullRightMainContent.CaraSalmonInfo, "InnerText", "Cara Salmon");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
